name: Prepare semantic release --dryRun
on:
  workflow_dispatch
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile --silent

      - name: Build affected libs
        # run: npx nx run chlorophyll:build
        run: npx nx affected --target build --base=origin/main

      - name: Prepare release of chlorophyll and extract
        run: npx nx run-many --target=version --projects=chlorophyll,extract --base=origin/main --dryRun
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          HUSKY: 0

      - name: Prepare release of charts
        run: npx nx run-many --target=prepare-release --projects=charts --base=origin/main --dryRun
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          HUSKY: 0

      - name: Prepare release of remaining libs
        run: npx nx run-many --target=prepare-release --projects=angular,angular-charts,react,react-charts --base=origin/main --dryRun
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          HUSKY: 0
